@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package limonblaze.blazereborn.common.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;