@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.limonblaze.blazereborn.common.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;