@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.limonblaze.blazereborn.common.effect;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;