@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package limonblaze.blazereborn.api.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;