@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.limonblaze.blazereborn.client.screen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;