@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package limonblaze.blazereborn.api.extension.fire;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;