@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package limonblaze.blazereborn.common.block.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;