@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.limonblaze.blazereborn.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;