@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package limonblaze.blazereborn.common.advancement.critereon;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;