@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.limonblaze.blazereborn.api.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;